### ISSUE TITLE
How to debug ?

### ISSUE THREAD

**Issue by ampsarfraz** [actionhero/actionhero#1150]
Hello,
We are trying to evaluate Actionhero for our project. Can you please let me know how to debug this? We are new to node and usually use node --inspect server.js. How to use it with the actionhero command?

Thank you.

**Comment by ampsarfraz** [comment]
I am trying it on windows and below is the error that I get when I run node ./node_modules/.bin/actionhero --inspect start

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by evantahler** [comment]
Oh, on windows there's some other executable to use, perhaps `./node_modules/.bin/actionhero.bin`?   I don't have access to a windows computer to check the exact path, but it should be there!

**Comment by S3bb1** [comment]
Hi,

you can simply use 

node --inspect node_modules/actionhero/bin/actionhero
