### ISSUE TITLE
Quick Start not working

### ISSUE THREAD

**Issue by hontas** [actionhero/actionhero#1151]
# Quick Start not working
Following the quick start does not work.
1. Running `npx actionhero generate` gives error `Cannot find module 'node_modules/.bin/actionhero'` (even though it's in there)
2. Running `npm start` repeats error:
```
10.5.57.148 @ 2017-11-09T14:59:34.376Z - error: Redis connection `client` error Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
```

- ActionHero Version: `18.0.2`
- Node.js Version: `8.4.0`
- Operating System: `(OSX, Ubuntu 14, Windows 10, etc)`

# Steps to reproduce your error
- Make sure redis is not installed/running on host
- Make a new actionhero project as described in Quick Start

# Solutions
1. Running `npx ./node_modules/.bin/actionhero generate` does work - note the './' before node_modules
2. ?

**Comment by evantahler** [comment]
Can you clarify that:
1) you have redis installed and it is running on the default ports?
2) that you are running on either OSX or Linux

**Comment by evantahler** [comment]
Or, are you suggesting that the quickstart include that redis should be running?  That's probably ta good idea...

**Comment by hontas** [comment]
1. I do not have redis installed at all.
This is what it sais in the quickstart-section of https://www.actionherojs.com/get-started/

`redis (for cluster support, cache, stats, and tasks); but not required`

Did I misinterpret this? Is it required?

2. Sorry, missed rhat one - I am running on OSX

**Comment by evantahler** [comment]
Ah! We should have a note about *how* to tell your project that you intend to skip redis: https://github.com/actionhero/www.actionherojs.com/commit/b3560e5acd031ee43c1257236e0a1e98ec7526ec

Regarding your other issue, I can't reproduce the error `Cannot find module`... can you confirm your steps look like the below?

```
[08:45:49] evan@evantop [~/Desktop]
> mkdir test
[08:45:51] evan@evantop [~/Desktop]
> cd test/
[08:45:52] evan@evantop [~/Desktop/test]
> node --version
v8.9.0
[08:46:00] evan@evantop [~/Desktop/test]
> npm --version
5.5.1
[08:46:02] evan@evantop [~/Desktop/test]
> npm install actionhero

> typechecker@2.0.8 preinstall /Users/evan/Desktop/test/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/evan/Desktop/test/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> actionhero@18.0.2 postinstall /Users/evan/Desktop/test/node_modules/actionhero
> echo 'To generate a new actionhero project, run "npx actionhero generate"'

To generate a new actionhero project, run "npx actionhero generate"
npm WARN saveError ENOENT: no such file or directory, open '/Users/evan/Desktop/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/evan/Desktop/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ actionhero@18.0.2
added 122 packages in 5.626s
[08:46:13] evan@evantop [~/Desktop/test]
> npx actionhero generate
Generating a new actionhero project...
created directory '/Users/evan/Desktop/test/actions'
created directory '/Users/evan/Desktop/test/pids'
created directory '/Users/evan/Desktop/test/config'
created directory '/Users/evan/Desktop/test/config/servers'
created directory '/Users/evan/Desktop/test/initializers'
created directory '/Users/evan/Desktop/test/log'
created directory '/Users/evan/Desktop/test/locales'
created directory '/Users/evan/Desktop/test/bin'
created directory '/Users/evan/Desktop/test/servers'
created directory '/Users/evan/Desktop/test/public'
created directory '/Users/evan/Desktop/test/public/javascript'
created directory '/Users/evan/Desktop/test/public/css'
created directory '/Users/evan/Desktop/test/public/logo'
created directory '/Users/evan/Desktop/test/tasks'
created directory '/Users/evan/Desktop/test/test'
wrote file '/Users/evan/Desktop/test/config/api.js'
wrote file '/Users/evan/Desktop/test/config/logger.js'
wrote file '/Users/evan/Desktop/test/config/redis.js'
wrote file '/Users/evan/Desktop/test/config/tasks.js'
wrote file '/Users/evan/Desktop/test/config/errors.js'
wrote file '/Users/evan/Desktop/test/config/plugins.js'
wrote file '/Users/evan/Desktop/test/config/i18n.js'
wrote file '/Users/evan/Desktop/test/config/routes.js'
wrote file '/Users/evan/Desktop/test/config/servers/socket.js'
wrote file '/Users/evan/Desktop/test/config/servers/web.js'
wrote file '/Users/evan/Desktop/test/config/servers/websocket.js'
wrote file '/Users/evan/Desktop/test/package.json'
wrote file '/Users/evan/Desktop/test/actions/status.js'
wrote file '/Users/evan/Desktop/test/actions/createChatRoom.js'
wrote file '/Users/evan/Desktop/test/actions/showDocumentation.js'
wrote file '/Users/evan/Desktop/test/public/index.html'
wrote file '/Users/evan/Desktop/test/public/chat.html'
wrote file '/Users/evan/Desktop/test/public/css/cosmo.css'
wrote file '/Users/evan/Desktop/test/public/logo/actionhero.png'
wrote file '/Users/evan/Desktop/test/README.md'
wrote file '/Users/evan/Desktop/test/test/example.js'
wrote file '/Users/evan/Desktop/test/locales/en.json'

Generation Complete.  Your project directory should look like this:

|- config
| -- api.js
| -- errors.js
| -- i18n.js
| -- logger.js
| -- redis.js
| -- routes.js
| -- tasks.js
| -- servers
| ---- web.js
| ---- websocket.js
| ---- socket.js
|-- (project settings)
|
|- actions
|-- (your actions)
|
|- initializers
|-- (any additional initializers you want)
|
|- log
|-- (default location for logs)
|
|- node_modules
|-- (your modules, actionhero should be npm installed in here)
|
|- pids
|-- (pidfiles for your running servers)
|
|- public
|-- (your static assets to be served by /file)
|
|- servers
|-- (custom servers you may make)
|
|- tasks
|-- (your tasks)
|
|- bin
|-- (your custom CLI commands)
|
|- locales
|-- (translation files)
|
|- tests
|-- (tests for your API)
|
readme.md
package.json

You may need to run `npm install` to install some dependancies alert
Run 'npm start' to start your server
[08:46:22] evan@evantop [~/Desktop/test]
> npm start

> my_actionhero_project@0.1.0 start /Users/evan/Desktop/test
> actionhero start

₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋
ACTIONHERO COMMAND >> start
⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻
192.168.7.25 @ 2017-11-10T16:46:26.319Z - notice: *** Starting ActionHero ***
192.168.7.25 @ 2017-11-10T16:46:26.320Z - notice: environment: development
192.168.7.25 @ 2017-11-10T16:46:26.321Z - notice: pid: 42154
192.168.7.25 @ 2017-11-10T16:46:26.321Z - notice: server ID: 192.168.7.25
192.168.7.25 @ 2017-11-10T16:46:26.338Z - info: actionhero member 192.168.7.25 has joined the cluster
192.168.7.25 @ 2017-11-10T16:46:26.342Z - notice: Starting server: `web` @ 0.0.0.0:8080
192.168.7.25 @ 2017-11-10T16:46:26.344Z - notice: Starting server: `websocket`
192.168.7.25 @ 2017-11-10T16:46:26.862Z - alert: *** ActionHero Started ***
```

**Comment by hontas** [comment]
Yes thank you! (documentation)
I guess the other part has to do with `npx` and not `actionhero`- wasn't aware of the npx-command until a few days ago.

**Comment by evantahler** [comment]
Just to confirm, is everything working for you now?

**Comment by hontas** [comment]
Thanks for your concern, actually since I ran in to this little wall I haven't had the time to keep playing around with it. But I will, eventually :)

**Comment by skpandey1294** [comment]
> my_actionhero_project@0.1.0 start /home/skpandey1294/Desktop/actionhero-movie-project
> node ./dist/server.js

2020-04-01T05:13:02.121Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
Unable to connect to Redis - please check your Redis config!
2020-04-01T05:13:02.124Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:07.128Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:07.131Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:07.232Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:07.235Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:07.386Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:07.388Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:07.590Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:07.592Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:07.843Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:07.845Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:08.146Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:08.147Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:08.498Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:08.501Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:08.902Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:08.904Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:09.356Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:09.358Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:09.860Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:09.862Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:10.413Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:10.416Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:11.018Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:11.020Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:11.672Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:11.674Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:12.375Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:12.378Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:13.129Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:13.131Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:13.933Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:13.935Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:14.787Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:14.789Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:15.690Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:15.693Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:16.644Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:16.646Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:17.648Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:17.651Z - info: Redis connection `client` reconnecting 
2020-04-01T05:13:17.652Z - emerg: Exception occurred in initializer `redis` during load 
2020-04-01T05:13:17.653Z - emerg: Error with initializer step: "initialize" 
2020-04-01T05:13:17.654Z - emerg: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/home/skpandey1294/Desktop/actionhero-movie-project/node_modules/ioredis/built/redis/event_handler.js:166:37)
    at Object.onceWrapper (events.js:428:26)
    at Socket.emit (events.js:321:20)
    at TCP.<anonymous> (net.js:668:12) 
2020-04-01T05:13:17.655Z - crit: Cannot shut down actionhero, not running 
2020-04-01T05:13:18.653Z - alert: Redis connection `client` errorconnect ECONNREFUSED 127.0.0.1:6379 errno=-111 code=ECONNREFUSED syscall=connect address=127.0.0.1 port=6379 stack=Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) 
2020-04-01T05:13:18.654Z - info: Redis connection `client` reconnecting 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my_actionhero_project@0.1.0 start: `node ./dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my_actionhero_project@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/skpandey1294/.npm/_logs/2020-04-01T05_13_18_684Z-debug.log

**Comment by evantahler** [comment]
Hi @skpandey1294! 
Can you confirm that your redis server is up and running?  `Error: connect ECONNREFUSED 127.0.0.1:6379` implies that actionhero cannot reach redis, which normaly runs on port 6379
