### ISSUE TITLE
Crash when a file gets changed in the project - Issue with hot reload

### ISSUE THREAD

**Issue by bhagaban** [actionhero/actionhero#1162]
# Issue with hot reload
The Actionhero server crashes when a initializer or config file gets changed while the server is running in development mode

```
node_modules/actionhero/initializers/config.js:63
            setTimeout(() => { api.watchedFiles[file].blocked = false }, 1000)
                                                              
TypeError: Cannot set property 'blocked' of undefined
    at Timeout.setTimeout [as _onTimeout] (*****/node_modules/actionhero/initializers/config.js:63:63)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```

- ActionHero Version: `18.1.0`
- Node.js Version: `8.8.1`
- Operating System: `(OSX)`

# Steps to reproduce your error
- Make a new actionhero project with `npx actionhero generate`
- Start the project - `npm start`
- Change a config file or initializer and save these files. Watch the terminal

---

**Comment by evantahler** [comment]
Interesting!  I cannot reproduce this using the same setup as you outline (osx, node v8.8.1, etc).  This might have to do with the part of the path you have replaced with ***.  Is your path lower case?  Have spaces?

**Comment by bhagaban** [comment]
![screen shot 2017-12-19 at 9 38 03 am](https://user-images.githubusercontent.com/826722/34140389-5db2f6c6-e4a0-11e7-8789-13447b5d8d06.png)
Hi @evantahler - Above is the actual screenshot with the actual path. The path has an Uppercase letter but it happens even with paths in lowercase.

**Comment by evantahler** [comment]
@bhagaban Can you share the full path of the file you are changing please?  
@crrobinson14 or @gcoonrod are you able to reproduce this?

**Comment by bhagaban** [comment]
@evantahler - The filepath is /Users/bhagaban/Projects/verifylabs-server/initializers/bigchaindb.js

**Comment by alimvedats** [comment]
same issue, when i changed the file, actionhero gives this error
because `api.unWatchAllFiles` called before this error

i was added throw for tests and logged `api.watchedFiles` and i saw `/node_modules/actionhero/initializers/config.js` in the list..

throw flow:
at Object.api.unWatchAllFiles (/app/node_modules/actionhero/initializers/config.js:77:13)
    at Config.stop (/app/node_modules/actionhero/initializers/config.js:202:9)
    at Utils.stopFunction (/app/node_modules/actionhero/classes/process.js:168:31)
    at Object.api.utils.asyncWaterfall (/app/node_modules/actionhero/initializers/utils.js:77:31)
    at Process.stop (/app/node_modules/actionhero/classes/process.js:249:25)
    at Process.restart (/app/node_modules/actionhero/classes/process.js:269:18)
    at Object.restart (/app/node_modules/actionhero/classes/process.js:37:50)
    at api.watchFileAndAct (/app/node_modules/actionhero/classes/process.js:131:30)
    at FSWatcher.fs.watch (/app/node_modules/actionhero/initializers/config.js:67:13)
    at FSWatcher.emit (events.js:159:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1379:12)

**Comment by evantahler** [comment]
Looking into the code, I don't think `block` is needed any more, because now we store and compare the file stats.

I'll remove it via https://github.com/actionhero/actionhero/pull/1163, and I think that should help.  There's no need for that setTimeout at all any more :/
