### ISSUE TITLE
No API Url prameter : TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by EpicKiwi** [actionhero/actionhero#1167]
# No API Url prameter : TypeError: Cannot read property 'slice' of null

When requesting an API Url without any parameter a fatal error occur.

- ActionHero Version: `17.1.1`
- Node.js Version: `9.3.0`
- Operating System: `Arch`

# Steps to reproduce
- Use any actionhero project even a newly generated
- Request an API URL without `?` in it

---

When requesting an API Url without any parameter i'm getting a fatal error of the web server
Nothing abnormal during starting of Actionhero.

```
./node_modules/actionhero/servers/web.js:493
      let search = connection.rawConnection.parsedURL.search.slice(1)
                                                             ^

TypeError: Cannot read property 'slice' of null
    at determineRequestParams (./node_modules/actionhero/servers/web.js:493:62)
    at api.GenericServer.server.on (./node_modules/actionhero/servers/web.js:250:5)
    at api.GenericServer.emit (events.js:159:13)
    at api.GenericServer.buildConnection (./node_modules/actionhero/initializers/genericServer.js:68:12)
    at browserFingerprint.fingerprint (./node_modules/actionhero/servers/web.js:336:14)
    at Object.fingerprint (./node_modules/browser_fingerprint/lib/browser_fingerprint.js:29:14)
    at handleRequest (./node_modules/actionhero/servers/web.js:272:24)
    at Server.server.server.http.createServer (./node_modules/actionhero/servers/web.js:44:9)
    at child.emit (./node_modules/eventemitter3/index.js:130:35)
    at child.request (./node_modules/primus/transformer.js:155:36)
```
I've tested on fresh new installations and with the tutorial code, same thing.
Everything works perfectly when I add a `?` at the end of the URL.

**Comment by evantahler** [comment]
This would be the same issue described in https://github.com/actionhero/actionhero/pull/1152 and https://github.com/actionhero/actionhero/pull/1153.

Per our policy of supporting v17 of ActionHero until [March of 2018](https://blog.evantahler.com/actionhero-v18-async-await-d88d369ed7b7), we'll need to merge this change into v17 as well

**Comment by evantahler** [comment]
will be solved by https://github.com/actionhero/actionhero/pull/1168
