### ISSUE TITLE
Problem in testing

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1194]
Hello!

I'm using AH 18.1.2 + node v8.9.4.
I wrote some test like explained in tutorial, but time to time i see such errors:
```
 ACTION: payInCreate Tests
    ✓ require all necessary input params
    ✓ respond P010 if cannot access to AccountService or it is broken
    ✓ respond P003 if cannot access to SecureStorage or it is broken (90ms)
    ✓ respond P002 if there is a database error (289ms)
    ✓ can create a payment (154ms)
    ✓ respond P005 if too many payments in short time (1005ms)

  ACTION: payInPay Tests
(node:14978) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): Error: Connection is closed.
(node:14978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14978) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Connection is closed.
    ✓ require all necessary input params (53ms)
    ✓ can create a payment (143ms)
    ✓ respond P002 if there is a database error (241ms)
    ✓ respond P006 if incorrect client ID (56ms)
    ✓ respond P006 if incorrect payment ID (45ms)
    ✓ respond P007 if payment not in NEW status (185ms)
    ✓ process payment if all OK (171ms)
```
and sometime I have failed tests, but when i run this test separately - all is OK. Can you help me?
Thank you!

**Comment by DoctorDimon** [comment]
All tests have same:
```
    before(async () => {
        if(process.env.NODE_ENV !== 'test') {
            throw new Error('Should have booted into the test env')
        }
        api = await actionhero.start();
        await api.models.payments.update({
            status: 'REJECTED'
        },{
            where: {
                status: 'NEW'
            }
        });
    });
    after(async () => {
        await actionhero.stop()
    });
```

**Comment by DoctorDimon** [comment]
After update to node v 8.10.0 - 
```
(node:16967) UnhandledPromiseRejectionWarning: Error: Connection is closed.
    at close (/var/easybits/PaymentGateway/node_modules/ioredis/lib/redis/event_handler.js:101:21)
    at Socket.<anonymous> (/var/easybits/PaymentGateway/node_modules/ioredis/lib/redis/event_handler.js:76:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:567:12)
```

**Comment by evantahler** [comment]
Are you running tasks in your test suite?  Perhaps there's a processor doing something in the background that isn't stopping properly?

**Comment by DoctorDimon** [comment]
I have more than 10 tasks in this project, but for test env, I set scheduler to false. Dont know what to do, sometimes all is Ok, simetimes I see errors...

**Comment by evantahler** [comment]
You'll need to provide a lot more information for us to be able to help:  Initializers, Tasks, config examples... I think the slack channel is a better forum to help you debug.

I'm going to close this issue. If you can create a test which reproduces this case, we can open a new issue.
