### ISSUE TITLE
Floating problem

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1219]
# Floating problem with resque
Hi! I wrote you before about strange error when AH start or stop, today i have cached he trace

```
SecureStorage @ 2018-05-17T14:57:39.504Z - alert: *** ActionHero Stopped ***
SecureStorage @ 2018-05-17T14:57:39.792Z - notice: *** Starting ActionHero ***
SecureStorage @ 2018-05-17T14:57:39.792Z - notice: environment: development
SecureStorage @ 2018-05-17T14:57:39.793Z - notice: pid: 10143
SecureStorage @ 2018-05-17T14:57:39.793Z - notice: server ID: SecureStorage
SecureStorage @ 2018-05-17T14:57:39.796Z - info: actionhero member SecureStorage has joined the cluster
(node:10143) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'multiWorkerAction' of undefined
    at MultiWorker.api.resque.multiWorker.on (/var/easybits/SecureStorage/node_modules/actionhero/initializers/resque.js:132:193)
    at emitTwo (events.js:126:13)
    at MultiWorker.emit (events.js:214:7)
    at MultiWorker.checkWraper (/var/easybits/SecureStorage/node_modules/node-resque/lib/multiWorker.js:165:10)
    at <anonymous>
(node:10143) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10143) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SecureStorage @ 2018-05-17T14:57:41.661Z - info: Executing (default): SELECT NOW()
SecureStorage @ 2018-05-17T14:57:41.701Z - notice: Starting server: `socket` @ 127.0.0.1:5003
SecureStorage @ 2018-05-17T14:57:41.702Z - notice: Starting server: `web` @ 0.0.0.0:8080
```

Unfortunately, I cant provide more information or test case? but maybe you will find what is wrong.
Thank you!

- ActionHero Version: `19.0.1`
- Node.js Version: `8.11.1`
- Operating System: `CentOS 7`

**Comment by evantahler** [comment]
it looks like you have some missing information in your `/config/tasks.js` file

https://github.com/actionhero/actionhero/blob/master/config/tasks.js#L9-L20

**Comment by DoctorDimon** [comment]
No, config is OK and up to date.

**Comment by evantahler** [comment]
If you can't share your config file, there's not much more help we can give.  That line is explicitly about reading a configuration option that comes from the config.
