### ISSUE TITLE
 unhandled rejection in cluster more

### ISSUE THREAD

**Issue by DoctorDimon** [actionhero/actionhero#1222]
#  unhandled rejection in cluster more
Hello! In cluster mode my application crashes sometimes, with message (in cluster log):
```
@ 2018-05-24T09:34:43.756Z - alert: worker #469 [9812]: unhandled rejection => {"reason":{},"p":{}}
```

Can you please help me, how to find out what is happening and how to fix it? In workers logs there are no errors at all.

- ActionHero Version: `19.0.1`
- Node.js Version: `8.11.2`
- Operating System: `CentOS 7`

**Comment by evantahler** [comment]
Can you share any more information?  Is this worker that crashed serving web traffic?  Running tasks? Connected to any database?

**Comment by evantahler** [comment]
Does your cluster ever reach equilibrium?  IE: do you ever see a line like this `10.219.5.146 @ 2018-05-24T16:09:04.251Z - notice: cluster equilibrium state reached with 8 workers`, indicating that the N workers your cluster expected to start, did?

**Comment by DoctorDimon** [comment]
I cant find out the reason it crashes. I have 2 workers, and cluster starts OK:
```
ACTIONHERO COMMAND >> start cluster
⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻
using default value of `actionhero-worker-` for `workerTitlePrefix`
PaymentGateway @ 2018-05-25T08:06:31.209Z - notice:  - STARTING CLUSTER -
PaymentGateway @ 2018-05-25T08:06:31.210Z - notice: pid: 5388
PaymentGateway @ 2018-05-25T08:06:31.211Z - info: starting worker #1
PaymentGateway @ 2018-05-25T08:06:32.196Z - info: [worker #1 (5402)]: starting
PaymentGateway @ 2018-05-25T08:06:32.200Z - info: actionhero member actionhero-worker-1 has joined the cluster
PaymentGateway @ 2018-05-25T08:06:32.494Z - info: [worker #1 (5402)]: started
PaymentGateway @ 2018-05-25T08:06:32.494Z - info: starting worker #2
PaymentGateway @ 2018-05-25T08:06:34.644Z - info: [worker #2 (5417)]: starting
PaymentGateway @ 2018-05-25T08:06:34.661Z - info: actionhero member actionhero-worker-2 has joined the cluster
PaymentGateway @ 2018-05-25T08:06:34.938Z - info: [worker #2 (5417)]: started
PaymentGateway @ 2018-05-25T08:06:34.938Z - notice: cluster equilibrium state reached with 2 workers
```
It can crash within a minutes or within a hours (>24). When it happens, I see this picture in cluster log:
```
PaymentGateway @ 2018-05-25T08:00:59.122Z - alert: worker #84 [1169]: unhandled rejection => {"reason":{},"p":{}}
PaymentGateway @ 2018-05-25T08:00:59.122Z - notice: cluster equilibrium state reached with 2 workers
PaymentGateway @ 2018-05-25T08:00:59.143Z - info: [worker #1 (1169)]: exited
PaymentGateway @ 2018-05-25T08:00:59.143Z - info: starting worker #1
PaymentGateway @ 2018-05-25T08:01:00.568Z - info: [worker #1 (3696)]: starting
PaymentGateway @ 2018-05-25T08:01:00.568Z - info: actionhero member actionhero-worker-1 has joined the cluster
PaymentGateway @ 2018-05-25T08:01:01.095Z - info: [worker #1 (3696)]: started
PaymentGateway @ 2018-05-25T08:01:01.095Z - notice: cluster equilibrium state reached with 2 workers
PaymentGateway @ 2018-05-25T08:03:59.390Z - alert: worker #86 [2877]: unhandled rejection => {"reason":{},"p":{}}
PaymentGateway @ 2018-05-25T08:03:59.411Z - notice: cluster equilibrium state reached with 2 workers
PaymentGateway @ 2018-05-25T08:03:59.412Z - info: [worker #2 (2877)]: exited
PaymentGateway @ 2018-05-25T08:03:59.412Z - info: starting worker #2
PaymentGateway @ 2018-05-25T08:04:01.073Z - info: [worker #2 (4613)]: starting
PaymentGateway @ 2018-05-25T08:04:01.088Z - info: actionhero member actionhero-worker-2 has joined the cluster
PaymentGateway @ 2018-05-25T08:04:01.584Z - info: [worker #2 (4613)]: started
PaymentGateway @ 2018-05-25T08:04:01.584Z - notice: cluster equilibrium state reached with 2 workers
```
and so on...

Both of workers are serving socket connections, and run tasks. Just before crash log:
```
actionhero-worker-2 @ 2018-05-25T03:54:45.054Z - info: [ task ] name=paymentsTransitBalanceStatus, duration=17, error=false
actionhero-worker-2 @ 2018-05-25T03:54:45.054Z - info: [ task ] name=paymentsWithdraw, duration=17, error=false
actionhero-worker-2 @ 2018-05-25T03:54:45.054Z - info: [ task ] name=paymentsInConfirmation, duration=17, error=false
actionhero-worker-2 @ 2018-05-25T03:54:45.054Z - info: [ task ] name=paymentsOutStatus, duration=17, error=false
actionhero-worker-2 @ 2018-05-25T03:54:45.055Z - info: [ worker ] job success high workerId=5, class=paymentsTransitBalanceStatus, queue=high, result=true
actionhero-worker-2 @ 2018-05-25T03:54:45.055Z - info: [ worker ] job success high workerId=2, class=paymentsWithdraw, queue=high, result=true
actionhero-worker-2 @ 2018-05-25T03:54:45.055Z - info: [ worker ] job success high workerId=1, class=paymentsInConfirmation, queue=high, result=true
actionhero-worker-2 @ 2018-05-25T03:54:45.055Z - info: [ worker ] job success high workerId=3, class=paymentsOutStatus, queue=high, result=true
actionhero-worker-1 @ 2018-05-25T03:54:45.058Z - info: [ task ] name=paymentsVerifyProcessing, duration=26, error=false
actionhero-worker-1 @ 2018-05-25T03:54:45.062Z - info: [ worker ] job success high workerId=3, class=paymentsVerifyProcessing, queue=high, result=true
actionhero-worker-1 @ 2018-05-25T03:54:45.063Z - info: [ task ] name=paymentsVerifyStatus, duration=22, error=false
actionhero-worker-1 @ 2018-05-25T03:54:45.063Z - info: [ task ] name=paymentsInProcessing, duration=22, error=false
actionhero-worker-1 @ 2018-05-25T03:54:45.063Z - info: [ task ] name=paymentsInStatus, duration=22, error=false
actionhero-worker-1 @ 2018-05-25T03:54:45.063Z - info: [ worker ] job success high workerId=4, class=paymentsVerifyStatus, queue=high, result=true
actionhero-worker-1 @ 2018-05-25T03:54:45.063Z - info: [ worker ] job success high workerId=2, class=paymentsInProcessing, queue=high, result=true
actionhero-worker-1 @ 2018-05-25T03:54:45.063Z - info: [ worker ] job success high workerId=5, class=paymentsInStatus, queue=high, result=true
actionhero-worker-1 @ 2018-05-25T03:54:47.999Z - info: actionhero member actionhero-worker-2 has joined the cluster
actionhero-worker-2 @ 2018-05-25T03:54:47.985Z - notice: *** Starting ActionHero ***
actionhero-worker-2 @ 2018-05-25T03:54:47.987Z - notice: environment: sandbox
actionhero-worker-2 @ 2018-05-25T03:54:47.987Z - notice: pid: 494
actionhero-worker-2 @ 2018-05-25T03:54:47.987Z - notice: server ID: actionhero-worker-2
PaymentGateway @ 2018-05-25T03:54:48.074Z - info: actionhero member actionhero-worker-2 has joined the cluster
actionhero-worker-2 @ 2018-05-25T03:54:48.031Z - info: actionhero member actionhero-worker-2 has joined the cluster
actionhero-worker-2 @ 2018-05-25T03:54:48.135Z - info: Executing (default): SELECT NOW()
actionhero-worker-2 @ 2018-05-25T03:54:48.143Z - info: resque scheduler started
actionhero-worker-2 @ 2018-05-25T03:54:48.145Z - notice: Starting server: `socket` @ 127.0.0.1:5004
actionhero-worker-2 @ 2018-05-25T03:54:48.290Z - alert: *** ActionHero Started ***
actionhero-worker-2 @ 2018-05-25T03:54:48.296Z - info: [ status ] status=NodeHealthy, uptime=6, eventLoopDelay=0.042, consumedMemoryMB=29.16, resqueTotalQueueLength=0
actionhero-worker-2 @ 2018-05-25T03:54:48.318Z - info: LINKUP: Hey! SecureStorage here!
actionhero-worker-2 @ 2018-05-25T03:54:48.324Z - info: LINKUP: Hey! ClientService here!
actionhero-worker-2 @ 2018-05-25T03:54:48.410Z - info: LINKUP: Hey! AccountService here!
actionhero-worker-2 @ 2018-05-25T03:54:48.648Z - info: [ worker ] started workerId=1
actionhero-worker-2 @ 2018-05-25T03:54:49.152Z - info: [ worker ] started workerId=2
actionhero-worker-2 @ 2018-05-25T03:54:49.655Z - info: [ worker ] started workerId=3
actionhero-worker-2 @ 2018-05-25T03:54:50.157Z - info: [ worker ] started workerId=4
actionhero-worker-2 @ 2018-05-25T03:54:50.594Z - info: [server: socket] new connection to=127.0.0.1
actionhero-worker-1 @ 2018-05-25T03:54:50.598Z - info: [server: socket] new connection to=127.0.0.1
actionhero-worker-2 @ 2018-05-25T03:54:50.600Z - info: [server: socket] new connection to=127.0.0.1
actionhero-worker-2 @ 2018-05-25T03:54:50.660Z - info: [ worker ] started workerId=5
actionhero-worker-1 @ 2018-05-25T03:55:10.299Z - info: [ status ] status=NodeHealthy, uptime=2819980, eventLoopDelay=0.021, consumedMemoryMB=29.66, resqueTotalQueueLength=0
```
After this both of workers stops executing tasks and the service become unusable. As I can see in last log, worker2 crashed, but I cant figure out why.

I hope you can help me, thank you!

**Comment by DoctorDimon** [comment]
I use `actionhero-node-client` for socket connections between services

**Comment by DoctorDimon** [comment]
Some more info - this happens only in services that uses tasks. Here is what I can find:
worker log:
```
actionhero-worker-1 @ 2018-05-25T08:57:02.831Z - info: This node is now the Resque scheduler master
```

cluster log:
```
10.10.15.12 @ 2018-05-25T08:57:02.887Z - alert: worker #1286 [12674]: unhandled rejection => {"reason":{},"p":{}}
```

**Comment by evantahler** [comment]
So it looks like you have a task that crashes your server.  Perhaps there is a certain combination of arguments which causes the problem.  You should be able to look in Redis to see the tasks that are being worked on at the time of the crash (they are probably still listed as "working" workers).  That might provide some guidance. 

Also, increase the verbosity of your task logging ([here](https://github.com/actionhero/actionhero/blob/master/config/tasks.js#L9-L19)).  I'll bet if you do you will see a job start, but never finish because it crashed.  That will narrow down where to start looking 

That said, this is very bad error message.

**Comment by evantahler** [comment]
note to self: https://github.com/nodejs/node/issues/9523#issuecomment-259303079 is an interesting way to get at better stack traces for uncaughtRejections... but there is a performance penalty

**Comment by DoctorDimon** [comment]
Thank you for advice. But I think the problem is not in task itself. I have one AH instance that have only one task (pereodic, without any params). Before crash happen, it runs absolutely normally more then 20K times. And I added `try catch` to all code that executes in task body.

It starts happening periodically when I moved to version 19, from 18. And in same time we have changed deploy logic, from restart to USR2 strategy.

So in next days I will:
1. Add process.on in workers, maybe it will catch something.
2. Will test system without USR2 restarts.
3. Will test system with downgrade to version 18.

Please, do not close this issue, I fill the problem is somewhere in node-resque or in resque initializer. I will try to find more information.

Thanx.

**Comment by DoctorDimon** [comment]
One more interesting thing! Service start to operate normally without restart if i remove `resque:worker` namespace and all it content from Redis. Any ideas? :)

**Comment by evantahler** [comment]
You last note really does indicate that there is some bad data/params that your workers are reading from redis.

**Comment by evantahler** [comment]
https://github.com/actionhero/actionhero/commit/12d258a9dcf48b8ca833aeb7cf3427c96fb497eb brings better stacktraces and logging to the cluster from uncaught exceptions

```bash
actionhero start cluster --workers 1
₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋
ACTIONHERO COMMAND >> start cluster
⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻
using default value of `actionhero-worker-` for `workerTitlePrefix`
192.168.7.25 @ 2018-05-26T20:21:26.843Z - notice:  - STARTING CLUSTER -
192.168.7.25 @ 2018-05-26T20:21:26.843Z - notice: pid: 43960
192.168.7.25 @ 2018-05-26T20:21:26.844Z - info: starting worker #1
192.168.7.25 @ 2018-05-26T20:21:27.213Z - info: [worker #1 (43961)]: starting
192.168.7.25 @ 2018-05-26T20:21:27.216Z - info: actionhero member actionhero-worker-1 has joined the cluster
192.168.7.25 @ 2018-05-26T20:21:27.823Z - info: [worker #1 (43961)]: started
192.168.7.25 @ 2018-05-26T20:21:27.823Z - notice: cluster equilibrium state reached with 1 workers
192.168.7.25 @ 2018-05-26T20:21:30.214Z - alert: [worker #1 (43961)]: unhandled rejection => Oh No!
192.168.7.25 @ 2018-05-26T20:21:30.214Z - alert: [worker #1 (43961)]:    Error: Oh No!
192.168.7.25 @ 2018-05-26T20:21:30.215Z - alert: [worker #1 (43961)]:        at Timeout.setTimeout [as _onTimeout] (/Users/evan/PROJECTS/actionhero/actionhero/bin/methods/start.js:136:16)
192.168.7.25 @ 2018-05-26T20:21:30.215Z - alert: [worker #1 (43961)]:        at ontimeout (timers.js:475:11)
192.168.7.25 @ 2018-05-26T20:21:30.215Z - alert: [worker #1 (43961)]:        at tryOnTimeout (timers.js:310:5)
192.168.7.25 @ 2018-05-26T20:21:30.215Z - alert: [worker #1 (43961)]:        at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by DoctorDimon** [comment]
Hi! Thanks!
I think this problems appears only when cluster is reloaded via USR2 command, because services that was hard restarted works fine, but I will monitor more days.

I update one AH instance with your update (loaded from master) and rebooted it via USR2, waiting for crash and report.

**Comment by DoctorDimon** [comment]
Got it!
```
10.10.15.12 @ 2018-05-27T13:29:59.817Z - notice: cluster equilibrium state reached with 2 workers
10.10.15.12 @ 2018-05-28T01:22:32.140Z - alert: [worker #2 (20218)]: unhandled rejection => Cannot destructure property `name` of 'undefined' or 'null'.
10.10.15.12 @ 2018-05-28T01:22:32.165Z - alert: [worker #2 (20218)]:    TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
10.10.15.12 @ 2018-05-28T01:22:32.166Z - alert: [worker #2 (20218)]:        at Scheduler.checkStuckWorkers (/var/opt/NotifyService/node_modules/actionhero/node_modules/node-resque/lib/scheduler.js:202:36)
10.10.15.12 @ 2018-05-28T01:22:32.166Z - alert: [worker #2 (20218)]:        at <anonymous>
10.10.15.12 @ 2018-05-28T01:22:32.167Z - notice: cluster equilibrium state reached with 2 workers
```

**Comment by DoctorDimon** [comment]
And this crash appears only is cluster is restarted via USR2 signal. Services that were restarted in hard way are working OK within last 48 hours.

**Comment by DoctorDimon** [comment]
One more, in worker
```
(node:3010) UnhandledPromiseRejectionWarning: Error: worker not found
    at Queue.forceCleanWorker (/var/easybits/UserAPI/node_modules/node-resque/lib/queue.js:250:26)
    at <anonymous>
(node:3010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3010) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by evantahler** [comment]
Ok, great research! These errors make sense after a USR2, as there may be a worker with a long-running job which is signaled to stop, takes too long, and is eventually force-killed.   Then, after an hour (which is the default), node resque will attempt to clean the old worker and move the task it was working on to the failure queue... and something is going wrong there.

Can you confirm that in your application you are not writing anything to redis that would match this glob `this.connection.key('worker', 'ping', '*')`?

**Comment by DoctorDimon** [comment]
I confirm. In my application I use only locks via api object.

**Comment by evantahler** [comment]
I've fixed a few small things in node-resque (https://github.com/taskrabbit/node-resque/releases/tag/v5.3.1) so we node-resque multiworkers, and therefore actionhero will now properly wait for a task that is being worked on to complete before exiting.  We may have had a case where there was some strange shutdown behavior in your app.

I've also added better logging of clearing stuck workers to ActionHero via https://github.com/actionhero/actionhero/pull/1223/files

Now, if you have a job that never ends: 
```js
// from tasks/verySlow.js
const ActionHero = require('actionhero')

module.exports = class MyTask extends ActionHero.Task {
  constructor () {
    super()
    this.name = 'verySlowTask'
    this.description = 'an actionhero task'
    this.frequency = 1000
    this.queue = 'defualt'
    this.middleware = []
  }

  timeout () {
    return 1000 * 60 * 60 // 1 hour
  }

  async run (data) {
    const timeout = this.timeout()
    await new Promise((resolve) => {
      setTimeout(resolve, timeout)
    })
  }
}
```

And you set `api.config.tasks.stuckWorkerTimeout = (1000 * 60)` (just to move things along faster)

You can run ActionHero once, and then try to stop it / restart it with any signal you like:

```bash
₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋
ACTIONHERO COMMAND >> start
⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻
actionhero @ 2018-05-29T03:02:58.172Z - notice: *** Starting ActionHero ***
actionhero @ 2018-05-29T03:02:58.173Z - notice: environment: development
actionhero @ 2018-05-29T03:02:58.174Z - notice: pid: 74796
actionhero @ 2018-05-29T03:02:58.174Z - notice: server ID: actionhero
actionhero @ 2018-05-29T03:02:58.188Z - info: actionhero member actionhero has joined the cluster
actionhero @ 2018-05-29T03:02:58.192Z - info: resque scheduler started
actionhero @ 2018-05-29T03:02:58.193Z - notice: Starting server: `web` @ 0.0.0.0:8080
actionhero @ 2018-05-29T03:02:58.195Z - notice: Starting server: `websocket`
actionhero @ 2018-05-29T03:02:58.871Z - alert: *** ActionHero Started ***
actionhero @ 2018-05-29T03:02:59.356Z - info: [ worker ] started workerId=1
actionhero @ 2018-05-29T03:03:03.198Z - info: This node is now the Resque scheduler master
^Cactionhero @ 2018-05-29T03:04:59.198Z - notice: stopping process...
actionhero @ 2018-05-29T03:04:59.201Z - info: resque scheduler ended
/Users/evan/PROJECTS/actionhero/actionhero/bin/methods/start.js:72
      throw new Error('process stop timeout reached.  terminating now.')
      ^

Error: process stop timeout reached.  terminating now.
    at Timeout.setTimeout [as _onTimeout] (/Users/evan/PROJECTS/actionhero/actionhero/bin/methods/start.js:72:13)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```
You will see that now ActionHero properly terminates itself with a long-running job after 30s (configurable via `process.env.ACTIONHERO_SHUTDOWN_TIMEOUT`).  We can now be sure that we have a "stuck worker" who was previously working on `verySlowTask`.

When you next start up ActionHero (and wait +1 minute), we can now see that the cleanup job happens, and there is no crash

```
₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋₋
ACTIONHERO COMMAND >> start
⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻
actionhero @ 2018-05-29T03:05:39.914Z - notice: *** Starting ActionHero ***
actionhero @ 2018-05-29T03:05:39.915Z - notice: environment: development
actionhero @ 2018-05-29T03:05:39.916Z - notice: pid: 74814
actionhero @ 2018-05-29T03:05:39.916Z - notice: server ID: actionhero
actionhero @ 2018-05-29T03:05:39.929Z - info: actionhero member actionhero has joined the cluster
actionhero @ 2018-05-29T03:05:39.932Z - info: resque scheduler started
actionhero @ 2018-05-29T03:05:39.934Z - notice: Starting server: `web` @ 0.0.0.0:8080
actionhero @ 2018-05-29T03:05:39.935Z - notice: Starting server: `websocket`
actionhero @ 2018-05-29T03:05:40.578Z - alert: *** ActionHero Started ***
actionhero @ 2018-05-29T03:05:41.067Z - info: [ worker ] started workerId=1
actionhero @ 2018-05-29T03:05:44.939Z - info: This node is now the Resque scheduler master
actionhero @ 2018-05-29T03:06:25.038Z - warning: cleaned stuck worker workerName=evan.local:74796+1, worker=evan.local:74796+1, queue=defualt, class=verySlowTask, queue=defualt, args=[], exception=Worker Timeout (killed manually), error=Worker Timeout (killed manually), backtrace=[killed by evan.local at Mon May 28 2018 20:06:25 GMT-0700 (PDT), queue#forceCleanWorker, node-resque], failed_at=Mon May 28 2018 20:06:25 GMT-0700 (PDT), delta=61
```

Give it a try please!

**Comment by DoctorDimon** [comment]
So I think the problem is now solved!!!
I have updated the heaviest instance which have more then 15 periodic tasks. Turn it on and restarted several times via USR2, and it work absolutely stable! Great! No more errors in cluster log, no in workers logs. I will monitor this instance for next 48 hours to be absolutely sure.

When changes in AH will be in release?

Thanks a lot! )))

**Comment by evantahler** [comment]
The main change was in node-resque.  Update that in your package.json, and you can use it now

**Comment by DoctorDimon** [comment]
Hi!
Sorry, but the problem still exists. Now I see this messages:
```
PaymentGateway @ 2018-06-01T10:12:33.589Z - alert: worker #22 [6857]: unhandled rejection => {"message":"worker not found","stack":["Error: worker not found","    at Queue.forceCleanWorker (/var/opt/EasyBits/PaymentGateway/node_modules/node-resque/lib/queue.js:250:26)","    at <anonymous>"]}
```
And again, service reboot worker at soon it become a resque master.

Please help! :)

**Comment by evantahler** [comment]
Moving the conversation to https://github.com/actionhero/actionhero/issues/1225
