### ISSUE TITLE
Not work resque_overrides

### ISSUE THREAD

**Issue by witem** [actionhero/actionhero#1235]
# `resque_overrides` in `config/tasks.js` not work if use classes

- ActionHero Version: `19.0.2`
- Node.js Version: `8.9.1`
- Operating System: `Arch Linux`

# Steps to reproduce your error
- Set `resque_overrides.queue` to some class
- Run `npm start`

---
Example(`config/tasks.js`):
```
const NodeResque = require('node-resque')

class Queue extends NodeResque.Queue {
    constructor(...args) {
        super(...args);
    }
}

exports.default = {
    tasks(api) {
        return {
            resque_overrides: {
                queue: Queue,
            },
         };
    },
};
```

Stack trace:
```
TypeError: Class constructor Queue cannot be invoked without 'new'
    at Object.api.utils.hashMerge (/app/node_modules/actionhero/initializers/utils.js:122:28)                                                                                                               
    at Object.api.utils.hashMerge (/app/node_modules/actionhero/initializers/utils.js:119:28)                                                                                                               
    at Object.api.utils.hashMerge (/app/node_modules/actionhero/initializers/utils.js:124:32)                                                                                                               
    at loadConfigFile (/app/node_modules/actionhero/initializers/config.js:145:62)
    at api.loadConfigDirectory (/app/node_modules/actionhero/initializers/config.js:159:11)                                                                                                                 
    at Array.map (<anonymous>)
    at Config.initialize (/app/node_modules/actionhero/initializers/config.js:219:17)
    at Process.initialize (/app/node_modules/actionhero/classes/process.js:75:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Error with initializer step: [object Object]
```

**Comment by evantahler** [comment]
You should be passing an instance of Queue, not construtor.

**Comment by witem** [comment]
@evantahler but in initialize it be called with `new`:
https://github.com/actionhero/actionhero/blob/4f9375253625e260ecdb9e8ea31b8674b962855f/initializers/resque.js#L40-L41

**Comment by gcoonrod** [comment]
We build up an instance of `Queue` in the Resque initializer. I don't think we have the necessary configuration information to pass to the constructor in the config file. We may need to treat these overrides similarly to how the Redis constructors are handled.

**Comment by witem** [comment]
@gcoonrod maybe in `api.utils.hashMerge` check if function `class` and don't call it, use simple reasign.

**Comment by witem** [comment]
I resolve it by adding hack(`queueOverride` function):
```
const NodeResque = require('node-resque')

class Queue extends NodeResque.Queue {
    constructor(...args) {
        super(...args);
    }
}

const queueOverride = () => Queue;

exports.default = {
    tasks(api) {
        return {
            resque_overrides: {
                queue: queueOverride,
            },
         };
    },
};
```

Issue may be closed. Thanks

**Comment by witem** [comment]
@gcoonrod @evantahler 
Maybe add overrides not for classes, but for options?

**Comment by witem** [comment]
@evantahler @gcoonrod ping

**Comment by gcoonrod** [comment]
@witem Apologies for the delay. I'll try and pick this back up shortly.

**Comment by evantahler** [comment]
The issues seems to be around knowing when to expand a class vs a function in api.utils.hashMerge.

There might be something to
```
> Object.getOwnPropertyNames(f)
[ 'length', 'name', 'arguments', 'caller', 'prototype' ]
> Object.getOwnPropertyNames(c)
[ 'length', 'prototype', 'name' ]
```

**Comment by witem** [comment]
You can try this:
```> c.toString()
"class someClass {}"
> f.toString()
"function () {}"
> a.toString()
"() => {}"```

**Comment by gcoonrod** [comment]
@evantahler Our assumption about the property names of a class vs a function doesn't seem to hold.

```js
test('class vs function', () => {
      let f = function () {}
      let k = class K {
        constructor () {
          this.a = 1
        }
      }
      let a = () => {}

      console.log('function')
      console.log(f)
      console.log(typeof f)
      console.log(Object.getOwnPropertyNames(f))
      console.log(api.utils.isFunctionNotClass(f))

      console.log('class')
      console.log(k)
      console.log(typeof k)
      console.log(Object.getOwnPropertyNames(k))
      console.log(api.utils.isFunctionNotClass(k))

      console.log('arrow')
      console.log(a)
      console.log(typeof a)
      console.log(Object.getOwnPropertyNames(a))
      console.log(api.utils.isFunctionNotClass(a))

      expect(api.utils.isFunctionNotClass(f)).toEqual(true)
      expect(api.utils.isFunctionNotClass(k)).toEqual(false)
      expect(api.utils.isFunctionNotClass(a)).toEqual(true)
      expect(api.utils.isFunctionNotClass({})).toEqual(false)
    })
```

logs the following and fails on the first assertion.

```bash
console.log __tests__/utils/utils.js:121
    function

  console.log __tests__/utils/utils.js:122
    [Function: f]

  console.log __tests__/utils/utils.js:123
    function

  console.log __tests__/utils/utils.js:124
    [ 'length', 'name', 'prototype' ]

  console.log __tests__/utils/utils.js:125
    false

  console.log __tests__/utils/utils.js:127
    class

  console.log __tests__/utils/utils.js:128
    [Function: K]

  console.log __tests__/utils/utils.js:129
    function

  console.log __tests__/utils/utils.js:130
    [ 'length', 'prototype', 'name' ]

  console.log __tests__/utils/utils.js:131
    false

  console.log __tests__/utils/utils.js:133
    arrow

  console.log __tests__/utils/utils.js:134
    [Function: a]

  console.log __tests__/utils/utils.js:135
    function

  console.log __tests__/utils/utils.js:136
    [ 'length', 'name' ]

  console.log __tests__/utils/utils.js:137
```

Note that both the function and the class report the same properties.

**Comment by gcoonrod** [comment]
https://stackoverflow.com/questions/30758961/how-to-check-if-a-variable-is-an-es6-class-declaration Gives some good context. Look in the comments of the second answer.

**Comment by witem** [comment]
@gcoonrod @evantahler any updates?

**Comment by evantahler** [comment]
Closing this issue due to inactivity.
