### ISSUE TITLE
Question: Is this right way to disable redis 

### ISSUE THREAD

**Issue by Mingyiz** [actionhero/actionhero#1277]
# config actionhero without redis
I am working with ActionHero without redis, I simply disable redis in config/redis.js.

If this is right way to configure actionhereo without redis, please let me known. Thanks.  

- ActionHero Version: `19.1.0`
- Node.js Version: `10.9.0`
- Operating System: `(Windows 7,  x86_64)`
- Windows default code page is 936 (chinese simple)

change config/redis.js as below
```js
exports['default'] = {
  redis: (api) => {
    // konstructor: The redis client constructor method.  All redis methods must be promises
    // args: The arguments to pass to the constructor
    // buildNew: is it `new konstructor()` or just `konstructor()`?

    function retryStrategy (times) {
      if (times === 1) {
        const error = 'Unable to connect to Redis - please check your Redis config!'
        if (process.env.NODE_ENV === 'test') { console.error(error) } else { api.log(error, 'error') }
        return 5000
      }
      return Math.min(times * 50, maxBackoff)
    }

    return {
      enabled: false, // only change this

      '_toExpand': false,
      client: {
        konstructor: require('ioredis'),
        args: [{ port: port, host: host, password: password, db: db, retryStrategy: retryStrategy }],
        buildNew: true
      },
      subscriber: {
        konstructor: require('ioredis'),
        args: [{ port: port, host: host, password: password, db: db, retryStrategy: retryStrategy }],
        buildNew: true
      },
      tasks: {
        konstructor: require('ioredis'),
        args: [{ port: port, host: host, password: password, db: db, retryStrategy: retryStrategy }],
        buildNew: true
      }
    }
  }
}
```

- start cmd, change the code page with chcp 65001
- npm start
 ```dos
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at WriteStream.Writable.write (_stream_writable.js:294:11)
    at Console.log (D:\github.com\webstreamer\webstreamer\node_modules\winston\lib\winston\transports\console.js:77:23)
    at Console._write (D:\github.com\webstreamer\webstreamer\node_modules\winston-transport\index.js:81:19)
    at doWrite (D:\github.com\webstreamer\webstreamer\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (D:\github.com\webstreamer\webstreamer\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Console.Writable.write (D:\github.com\webstreamer\webstreamer\node_modules\readable-stream\lib\_stream_writable.j
s:334:11)
    at DerivedLogger.ondata (D:\github.com\webstreamer\webstreamer\node_modules\readable-stream\lib\_stream_readable.js:
619:20)
    at DerivedLogger.emit (events.js:182:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webstreamer@0.1.0 start: `actionhero start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webstreamer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mingyi\AppData\Roaming\npm-cache\_logs\2018-12-18T23_34_34_877Z-debug.log
[2018-12-18T23_34_34_877Z-debug.log](https://github.com/actionhero/actionhero/files/2692653/2018-12-18T23_34_34_877Z-debug.log)
```

**Comment by evantahler** [comment]
Can you share your error trace with us?  Can you confirm that you have nothing running which relies on Redis existing?

**Comment by Mingyiz** [comment]
May be I  confused you, there are 2 point in this isuee
1.  Is it a right way to disable redis ( I confirm my project is not relies on Redis for now)
2.  npm start  failed
    But after dig a while, I found this releated to my eniroment changes.
   I install the node in windows **code page 936**, and install/run actionhero and my project in **code page 65001** command, the error is come out.  **I believe this not issue of actionhero**, so it is not problem for me now ( I will do all the work in same code page).

**Comment by evantahler** [comment]
The proper way to disable the reliance no redis is enabled = false, as you have found.

I don't know what a code page is, but good luck!  You can join us on slack.actionherojs.com to ask the community for help.
