### ISSUE TITLE
HTTP error if code in error NaN

### ISSUE THREAD

**Issue by witem** [actionhero/actionhero#1352]
# HTTP error if code in error NaN
After update to 20.*.* if server `throw new Error()` with `code: NaN` throws unhandled promise rejection. Logs:
```
(node:803571) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: NaN                                                                                                  
    at ServerResponse.writeHead (_http_server.js:209:11)                                                                                                                                                             
    at WebServer.sendWithCompression (/project/node_modules/actionhero/servers/web.js:259:38)                                                                                              
    at WebServer.sendMessage (/project/node_modules/actionhero/servers/web.js:119:10)                                                                                                      
    at WebServer.completeResponse (/project/node_modules/actionhero/servers/web.js:394:10)                                                                                                 
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```

- ActionHero Version: `20.0.0`
- Node.js Version: `10.15.1`
- Operating System: `Arch Linux`

# Steps to reproduce your error
- Throw new Error with `code: NaN`

**Comment by evantahler** [comment]
Oh, are you suggesting we should really `throw` and not have an unresolved promise?

**Comment by witem** [comment]
> Oh, are you suggesting we should really `throw` and not have an unresolved promise?

yes

And with `null` and `undefined` behavior expected. But with `NaN` it unexpected becaus try set `NaN` to http response code

**Comment by evantahler** [comment]
@witem let me know if you need help patching this and creating a test cast!

**Comment by evantahler** [comment]
I think I'm still confused about how you found this state.  Can you please provide a sample action that reproduces this behavior?

If you were to make an error in an action with a non-intenger code, i.e. 
```js
error = Error('nope')
error.code = 'not-a-number'
throw error
```

it would still fail the numeric range check https://github.com/actionhero/actionhero/blob/master/servers/web.js#L347-L363 and `isValidCustomResponseCode` would be false, so we would just return a HTTP status code of 500 (line 358)

**Comment by witem** [comment]
I try create test case

**Comment by evantahler** [comment]
Ping! 
Were you able to create a test case?

**Comment by witem** [comment]
I apologize for the delay, I was on vacation.

**Comment by witem** [comment]
@evantahler seems all work fine. I can't reproduce this error. Sorry and thanks
