### ISSUE TITLE
Wrong response logging with custom error handler

### ISSUE THREAD

**Issue by witem** [actionhero/actionhero#1509]
# Wrong response logging with custom error handler

If server use custom error formatter in logs we don't see correct response. Code for reproduce: https://github.com/witem/actionhero/commit/554153c07e8245b856848fee62b2536e97ec44fc .

When I run  `curl http://localhost:8080/api/testAppErr`, receive:

```
"error": {
    "code": "100500",
    "message": "some app error"
  },
```

But in console:

```
error: [ action @ web ] to=127.0.0.1 action=testAppErr params={"action":"testAppErr","apiVersion":1} duration=3 error=AppError: some app error response={"error":{"name":"AppError","appCode":"100500"}} name=AppError appCode=100500 stack=AppError: some app error
    at TestAppError.run (/home/ark/projects/git-projects/actionhero/src/actions/randomNumber.ts:43:17)
    at ActionProcessor.runAction (/home/ark/projects/git-projects/actionhero/src/classes/actionProcessor.ts:381:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at WebServer.processAction (/home/ark/projects/git-projects/actionhero/src/classes/server.ts:229:18) 

```

When I run  `curl http://localhost:8080/api/testErr`, receive:

```
"error": {
    "code": 500,
    "message": "Internal server error"
  }
```

But in console:

```
error: [ action @ web ] to=127.0.0.1 action=testAppErr params={"action":"testAppErr","apiVersion":1} duration=2 error=AppError: some app error response={"error":{"name":"AppError","code":"100500"}} name=AppErro
r code=100500 stack=AppError: some app error                                                                                                                                                                                                 
    at TestAppError.run (/home/ark/projects/git-projects/actionhero/src/actions/randomNumber.ts:43:17)                                                                                                                                       
    at ActionProcessor.runAction (/home/ark/projects/git-projects/actionhero/src/classes/actionProcessor.ts:381:35)                                                                                                                          
    at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                                                                                                                      
    at WebServer.processAction (/home/ark/projects/git-projects/actionhero/src/classes/server.ts:229:18)

```

- Actionhero Version: `23.0.0`
- Node.js Version: `12.18.0`
- Operating System: `Manjaro 5.7.0`

# Steps to reproduce your error

Example changes in: https://github.com/witem/actionhero/commit/554153c07e8245b856848fee62b2536e97ec44fc
* `curl http://localhost:8080/api/testAppErr`
* `curl http://localhost:8080/api/testErr`

**Comment by evantahler** [comment]
@witem could this be related https://github.com/actionhero/actionhero/pull/1558 ?

**Comment by witem** [comment]
> @witem could this be related #1558 ?

No, it didn't help. Response logging and error logging processed on `actionProcessor` level(https://github.com/actionhero/actionhero/blob/master/src/classes/actionProcessor.ts#L129). But final error response generating only after error serializer(https://github.com/actionhero/actionhero/blob/master/src/servers/web.ts#L520).

For resolve this, maybe need move logging from actionProcessor level to server level. It also helps with correct exception handling after actionProcessor on server level.

**Comment by evantahler** [comment]
Perhaps this could be rolled into https://github.com/actionhero/actionhero/discussions/1561 ?

**Comment by witem** [comment]
> Perhaps this could be rolled into #1561 ?

#1561 it's very great feature for us. But it can't resolve this issue, because in the case of #1509  we're changing the answer after logging it.  It's not critical issue but as example in some edge case Actionhero can log action as success, but something will break at the server level and user don't receive success response. For resolve this issue maybe need move logging action result only after sending server response.

**Comment by gcoonrod** [comment]
@witem does #1570 resolve your issue?

**Comment by witem** [comment]
> @witem does #1570 resolve your issue?

No, it doesn't

**Comment by gcoonrod** [comment]
@witem What is still missing from the current ActionProcessor error serializer? From my reading of your example code it seems like it would address the issue.

**Comment by witem** [comment]
@gcoonrod I describe why in comments to Evan. Even with #1570 global flow doesn't changed. And logging about action result occurs before the server format and finish respond. It is not critical issue, but actionhero user must should be aware of such exceptions

**Comment by gcoonrod** [comment]
@witem Looking again at the description of the problem. When you called `api/testErr` the console log says the action run was `testAppErr`. Is that the log line you meant to post?

**Comment by witem** [comment]
@gcoonrod it's error in description.

When I call `curl http://localhost:8080/api/testAppErr`:
Response:
```
{
  "error": {
    "code": "100500",
    "message": "some app error"
  },
}
```

Loggs:
```
2020-09-12T15:04:00.308Z - error: [ action @ web ] to=127.0.0.1 action=testAppErr params={"action":"testAppErr","apiVersion":1} duration=3 error=AppError: some app error response={"error":{"name":"AppError","appCode":"100500"}} name=AppError appCode=100500 stack=AppError: some app error
    at TestAppError.run (/home/ark/projects/git-projects/actionhero/src/actions/randomNumber.ts:43:17)
    at ActionProcessor.runAction (/home/ark/projects/git-projects/actionhero/src/classes/actionProcessor.ts:393:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at WebServer.processAction (/home/ark/projects/git-projects/actionhero/src/classes/server.ts:229:18)
```

When I call `curl http://localhost:8080/api/testErr`:
Response:
```
{
  "error": {
    "code": 500,
    "message": "Internal server error"
  },
}
```

Logs:
```
2020-09-12T15:06:28.393Z - error: [ action @ web ] to=127.0.0.1 action=testErr params={"action":"testErr","apiVersion":1} duration=1 error=Error: some internal error response={"error":{}} stack=Error: some internal error
    at TestError.run (/home/ark/projects/git-projects/actionhero/src/actions/randomNumber.ts:29:11)
    at ActionProcessor.runAction (/home/ark/projects/git-projects/actionhero/src/classes/actionProcessor.ts:393:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at WebServer.processAction (/home/ark/projects/git-projects/actionhero/src/classes/server.ts:229:18)
```

As result in first(`testAppErr`) and in second(`testErr`) we have wrong response logging

**Comment by gcoonrod** [comment]
@witem thanks for the correction. Just to be clear, what is the logging output that you would _like_ to see? Are you expecting the `some internal error` and its associated stack trace to come out in the server response?

**Comment by witem** [comment]
@gcoonrod I expect to see in the logs a response similar to the one that comes to the client. 
Example: 

- testErr - **`response={"error":{ "code": 500, "message": "Internal server error"}}`**
- testAppErr - **`response={"error":{ "code": 100500, "message": "some app error"}}`**

**Comment by gcoonrod** [comment]
@witem thanks for the clarification!

**Comment by evantahler** [comment]
@witem we think that #1661 solves this - can you try out the changes there and let us know?

**Comment by witem** [comment]
@evantahler yeah! Seems it work, thanks!
