### ISSUE TITLE
Actions not working with disabled redis

### ISSUE THREAD

**Issue by adascal** [actionhero/actionhero#1646]
# Actions not working with disabled redis

If I disable redis, actions are not working

- Actionhero Version: `24.0.3`
- Node.js Version: `v15.0.1` (doesn't matter)
- Operating System: `(OSX)`

# Steps to reproduce your error

- Make a new actionhero project with `npx actionhero generate`
- Open src/config/redis.ts and put `enabled: false`
- Start dev server (`npm run dev`)
- Open http://localhost:8080/api/status to see error

Example response:
```
{
  "error": "Cannot read property 'queue' of undefined",
  "serverInformation": {
    "serverName": "my_actionhero_project",
    "apiVersion": "0.1.0",
    "requestDuration": 13,
    "currentTime": 1604935169018
  },
  "requesterInformation": {
    "id": "59b239307751fa49504283c23f4c25b6b40ba368-8ad31bb9-cbfa-4d2f-9dae-b6c626680b8a",
    "fingerprint": "59b239307751fa49504283c23f4c25b6b40ba368",
    "messageId": "8ad31bb9-cbfa-4d2f-9dae-b6c626680b8a",
    "remoteIP": "127.0.0.1",
    "receivedParams": {
      "action": "status"
    }
  }
}
```

Stacktrace:
```
2020-11-09T15:19:29.017Z - error: [ action @ web ] to=127.0.0.1 action=status params={"action":"status","apiVersion":1} duration=2 error=TypeError: Cannot read property 'queue' of undefined stack=TypeError: Cannot read property 'queue' of undefined
    at Object.allWorkingOn (my_actionhero_project/node_modules/actionhero/dist/modules/task.js:180:35)
    at Object.details (my_actionhero_project/node_modules/actionhero/dist/modules/task.js:292:38)
    at Status.run (my_actionhero_project/src/actions/status.ts:46:32)
    at ActionProcessor.runAction (my_actionhero_project/node_modules/actionhero/dist/classes/actionProcessor.js:333:66)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at WebServer.processAction (my_actionhero_project/node_modules/actionhero/dist/classes/server.js:131:22) 
```

**Comment by evantahler** [comment]
Thanks for finding this @adascal!   This error comes from the `status` action trying to provide information about your resque queues / background tasks... which are disabled without redis.  We'll skip this check with https://github.com/actionhero/actionhero/pull/1647

**Comment by evantahler** [comment]
@adascal to get the fix right now, swap the contents of `src/actions/status.ts` with the changes in #1647.   Once the PR is merged in, you will still need to update your project's action.

**Comment by adascal** [comment]
Got it! Thanks. Cause I just started, `status` was my first action I played with
