### ISSUE TITLE
Cannot overwrite client JS in tests

### ISSUE THREAD

**Issue by evantahler** [actionhero/actionhero#1965]
# Cannot overwrite client JS in tests

Intermittently, our CI tests fail because we can't overwrite the client-side js

- Actionhero Version: `v27.1.2` 

# Steps to reproduce your error

```
 FAIL  __tests__/tasks/recordProperty/importRecordProperties.ts (18.271 s)
  ● Console

    console.log
      2021-09-21T00:29:25.375Z - alert: Cannot write client-side JS for websocket server: EEXIST: file already exists, mkdir '/home/circleci/project/core/public/client-js/' errno=-17 syscall=mkdir code=EEXIST path=/home/circleci/project/core/public/client-js/ stack=Error: EEXIST: file already exists, mkdir '/home/circleci/project/core/public/client-js/'
          at Object.mkdirSync (node:fs:1334:3)
          at WebSocketServer.writeClientJS (/home/circleci/project/node_modules/.pnpm/actionhero@27.1.2/node_modules/actionhero/dist/servers/websocket.js:159:24)
          at WebSocketServer.start (/home/circleci/project/node_modules/.pnpm/actionhero@27.1.2/node_modules/actionhero/dist/servers/websocket.js:37:14)
          at Servers.start (/home/circleci/project/node_modules/.pnpm/actionhero@27.1.2/node_modules/actionhero/dist/initializers/servers.js:82:30)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at startFunction (/home/circleci/project/node_modules/.pnpm/actionhero@27.1.2/node_modules/actionhero/dist/classes/process.js:126:29)
          at Process.start (/home/circleci/project/node_modules/.pnpm/actionhero@27.1.2/node_modules/actionhero/dist/classes/process.js:202:17)
          at /home/circleci/project/plugins/@grouparoo/spec-helper/dist/lib/specHelper.js:169:13

      at Console.log (../node_modules/.pnpm/winston@3.3.3/node_modules/winston/lib/winston/transports/console.js:79:23)
```

---

If your "issue" does not fit into this template, it might not be an issue! Please join our [slack team](http://slack.actionherojs.com) and ask the question of the community. We can help!

**Comment by evantahler** [comment]
This is likely a race-condition caused by a few test processes trying to create the directory at the same time
